### ISSUE TITLE
protostuff 反序列化报错

### ISSUE THREAD

**Issue by byene0923** [0yuyuko0/raftkv#1]
文件:
ProtostuffCodeC

代码：
ProtostuffCodeC中的main函数中代码运行报错

报错信息:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.dyuproject.protostuff.runtime.PolymorphicThrowableSchema (file:/Users/byene/.m2/repository/com/dyuproject/protostuff/protostuff-runtime/1.1.3/protostuff-runtime-1.1.3.jar) to field java.lang.Throwable.cause
WARNING: Please consider reporting this to the maintainers of com.dyuproject.protostuff.runtime.PolymorphicThrowableSchema
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.RuntimeException: The root object can neither be an abstract class nor interface: "java.util.List
	at com.dyuproject.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:195)
	at com.dyuproject.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:171)
	at com.dyuproject.protostuff.runtime.IdStrategy.newSchema(IdStrategy.java:72)
	at com.dyuproject.protostuff.runtime.DefaultIdStrategy$LazyRegister.getSchema(DefaultIdStrategy.java:661)
	at com.dyuproject.protostuff.runtime.RuntimeSchema.getSchema(RuntimeSchema.java:134)
	at com.dyuproject.protostuff.runtime.RuntimeSchema.getSchema(RuntimeSchema.java:126)
	at com.yuyuko.raftkv.remoting.protocol.codec.ProtostuffCodec.decode(ProtostuffCodec.java:52)
	at com.yuyuko.raftkv.remoting.protocol.codec.ProtostuffCodec.main(ProtostuffCodec.java:80)

**Comment by jyulei** [comment]
com.yuyuko.selector selector 这个依赖找不到该咋办
